# Generated by Django 5.0.2 on 2024-04-02 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='cgpa',
        ),
    ]
