# Generated by Django 5.0.2 on 2024-04-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_remove_record_cgpa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='Achievements',
            new_name='achievement',
        ),
        migrations.AddField(
            model_name='record',
            name='cgpa',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
