# Generated by Django 5.0.2 on 2024-04-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_rename_achievements_record_achievement_record_cgpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='Conference',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='record',
            name='Entreprenuership',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='record',
            name='ExtraCurricular',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='record',
            name='HigherStudies',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='record',
            name='Internship',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='record',
            name='Placement',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='record',
            name='PractiseSchool',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='record',
            name='Publications',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
