# Generated by Django 5.0.2 on 2024-07-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_record_conference_record_entreprenuership_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='Conference',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='Entreprenuership',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='ExtraCurricular',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='HigherStudies',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='Internship',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='Placement',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='PractiseSchool',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='Publications',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='achievement',
            field=models.FileField(upload_to=''),
        ),
    ]
